import Head from 'next/head';
import Link from 'next/link';

const patientCoreVideoLinks = [
  { name: 'Waiting Room', href: '/patient/video/waiting-room' },
  { name: 'Video Consultation', href: '/patient/video' },
  { name: 'Disconnected', href: '/patient/video/disconnected' },
  { name: 'No Mic/Video Permissions', href: '/patient/video/no-av-permission' },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Twilio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="p-4">
        <h1 className="mb-4 text-2xl">Sitemap</h1>

        <h2 className="mb-2 text-xl">Patient Core Video</h2>
        <ul className="pl-4">
          {patientCoreVideoLinks.map((link, i) => (
            <li key={i}>
              <Link href={link.href} passHref>
                <a className="text-blue-500">{link.name}</a>
              </Link>
            </li>
          ))}
        </ul>
      </div>
    </>
  );
}
